[tool.poetry]
name = "shankarlohar"
version = "0.1.1"
description = ""
authors = ["shankarlohar <inbox.shankarlohar@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12.2"


[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
